### ISSUE TITLE
There is problem with the programming style 

### ISSUE THREAD

**Issue by gordon518** [forthealllight/redux-saga-example#1]
This is a simple demo for redux-saga. But the source code looks like very complicated. The writer used too many folders, each folder only has one or two files. It's not easy to read source code when there is always the same name of index.js in each folder. Using as less folder as possible should be the rule for good programming style.

**Comment by forthealllight** [comment]
> This is a simple demo for redux-saga. But the source code looks like very complicated. The writer used too many folders, each folder only has one or two files. It's not easy to read source code when there is always the same name of index.js in each folder. Using as less folder as possible should be the rule for good programming style.

yes , in some ways, you are right
